#+title:LLM Investigacion
#+author:Alberto Emiliano Solis Santos
* Que es lo que es un NLP?
Un NLP basicamente es un modelo de machine learning enfocado a todo lo relacionado con el lenguaje humano


** para que sirven los NLP?
los NLP tiene tareas basntate claras:
- la clasificacion de oraciones
- generar texto
- extraer una respuesta de un texto 


* Que es un LLM
basicamente son similares a los modelos NLP pero son mucho mas grandes y con mas entrenamiento y mas capacidada parra realizar
tareas no especificas


** Caracteristicas de un LLM
- Escalado
- capacidades generadas
- aprendizaje en contexto


** limitaciones de LLM
- alucinaciones
- falta de entendimiento
- consumo computacional


* Transformer
los transformer son la arquitectura en que los LLM estan basados son NLP gigantes multiproposito pueden autocompletas palabras o intentar predecir oraciones futuras
asi como intentar predecir palabras especificas en una oracion


** tipos de aprendizaje
existen 2 tipos principales de aprendizaje cada uno con sus ventajas y desventajas de una forma mas generalizada sabemos esto:
- Pretaining: el pretraining es le acto de entrenar un modelo desde cero con sus pesos ajustados de manera aleatoria y se van
  ajustando a medida que es entrenado
- Fine-tuning: es el entrenamiento de un modelo preentrenado con data especifica para realizar la tarea especifica a realizar


** arquitectura
la arquitectura de los transformers consiste en 2 bloques los cuales son el *encoder* y el *decoder*.
- encoder: es la capa que recibe el input y lo transforma en a una represetacion
- decoder: se encarga de trabajar con la representacion del encoder y brinda un output en para la tarea objetivo

la arquictetura de los modelos puede variar pero siempre usan almenos uno de estos dos bloques en su arquitectura. Hay modelos
que solo usan una de estas capas esto depende de el objetivo y la tarea de dichos modelos
- solo encoder: cuando un modelo usa de arquitectura solo en encoder este mismo solo suele usarse para tareas que requieran un buen
  entendiemiento del input asi como clasificaciones de palabras o nombrar entidades del mismo input
- solo decoder: suelen usarse en tareas como la generaciones de texto
- ambos: sueln ser usados en tareas que requieren un input y un output como lo pueden ser resumenes o traducciones


*** checkpoints
un concepto a destacar son los *checkpoints* los cuales son pesos preentrenados que seran cargados en un arquitectura.
suelen ser confundidos con la misma *arquitectura* del modelo pero son conceptos totalmente diferentes


** atention layer
la capa de atencion es el comportamiento sobre el modelo que hace que le ponga mas o menos atencion a algunas palabras esto es util
para traducir cosas o realizar tareas especificas 


** atention mask
similar a la capa de atencion la mascara de atencion sirve para poder dar mas enfasis o quitar enfasis a palabras especificas


* Cuantizacion
la cuantizacion es la compresion del modelo se puede tener un modelo el cual pese muchisimo menos dando resultados
similares al modelo completo.


** Como funciona?
la Cuantificazion funciona reduciendo la cantidad de bits de informacion se almacenan de cada dato haciendo que de
mas presicion en cada uno de estos un ejemplo seria si un dato normalmente se guarda dentro de 16 bits entonces
si se este mismo se comprime se puede llegar a usar 8 bits o incluso menos (aun que esto no es tan recomendable)


** Nomenglaturas
terminologias que se usan para poder entender como y para que esta comprimido el modelo en cuestion son llamadas
*nomenglaturas*

| Nomenglatura  | Descripcion                             |
|---------------+-----------------------------------------|
| BF16 / FP16   | Es el modelo sin ninguna compresion     |
| MLX           | Compresion diseñada para chips de Apple |
| GGUF          | Para cualquier tipo de equipo           |
| AWQ           | Formato viejo para compresion de Apple  |
| GTPQ          | Para tarjetas NVIDIA                    |
| FP8           | para tarjetas nuevas                    |
| NVFP4 / MXFP4 | Para BlackWell                          |


** Cosas a considerar
entonces porque no siempre escojemos el formato mas comprimido de todos? para responder esta pregunta 
es necesario entender que no siempre mas pequeño significa mas rapido puede ser que el el procesador con el que
se trabaje no tenga rutinas para manejar el numero de bits en que se encuentran en el formato entonces el estos
se descomprimen y luego se opera con ellos esto da como resultado que el proceso llegue incluso a alentarse!

tambien entre mas comprimido sea el modelo mas tiende a atontarse lo cual en tareas sensibles no es aceptable tener
un margen de error alto.


* Pensamientos
RAG son LLM pero si es que el modelo no es LLM aun asi podremos generar una arquitectura para el uso de una fuente
de datos externa para poder realizar esto mismo? me explico lo que agus quiere es un LLM? o un NLP? porque un LLM
esta hecho para engrentar tareas no especificas esto da como 
